version: "3.6"

services:
    blog_web:
      image: blog
      depends_on:
        - blog_db
      ports:
        - "8000:80"
      volumes:
        - /home/$USER/source/markdown-blog-api:/opt/source/markdown-blog-api
      networks:
        - blog-network
    blog_db:
      image: blog-db
      command: --max_allowed_packet=128M --default-authentication-plugin=mysql_native_password
      ports:
        - "3306:3306"
      networks:
        - blog-network
      volumes:
        - blog-db-data:/var/lib/mysql

volumes:
  blog-db-data:
    driver: local
networks:
  blog-network:
    driver: bridge